#!/usr/bin/env bash

if [ "$1" == "bootstrap" ]
    then
        ./scripts/run.sh composer install && \
        sudo chown -R $(id -u):$(id -g) vendor
    exit
fi

if [ "$1" == "test" ]
    then
        ./scripts/run.sh ./vendor/bin/phpunit ${@:2}
    exit
fi

if [ "$1" == "testf" ]
    then
        ./cli test --filter="'${*:2}'"
    exit
fi

if [ "$1" == "testg" ]
    then
        ./cli test --group="'${*:2}'"
    exit
fi

./scripts/run.sh $@