#!/usr/bin/env bash

if [ "$1" == "bootstrap" ]
    then
        ./scripts/bootstrap.sh
    exit
fi

if [ "$1" == "test" ]
    then
        ./cli ./vendor/bin/phpunit ${@:2}
    exit
fi

if [ "$1" == "testf" ]
    then
        ./cli test --filter="'${*:2}'"
    exit
fi

if [ "$1" == "testg" ]
    then
        ./cli test --group="'${*:2}'"
    exit
fi

./scripts/run.sh $@